//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ListarProductosDisponibles_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_ListarProductosDisponibles_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                                                         __o = Url.Action("CerrarSesion", "Home");


#line default
#line hidden

#line 3 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                foreach (var item in Model)
                {
                    

#line default
#line hidden

#line 4 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                              __o = Html.DisplayFor(modelItem => item.IdProveedorProducto);


#line default
#line hidden

#line 5 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.IdProducto);


#line default
#line hidden

#line 6 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Nombre);


#line default
#line hidden

#line 7 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Longitud);


#line default
#line hidden

#line 8 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Diametro);


#line default
#line hidden

#line 9 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                           __o = Html.DisplayFor(modelItem => item.PrecioCompra);


#line default
#line hidden

#line 10 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                           __o = Html.DisplayFor(modelItem => item.Producto.PrecioVenta);


#line default
#line hidden

#line 11 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Stock);


#line default
#line hidden

#line 12 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Tipo.Tipo);


#line default
#line hidden

#line 13 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Proveedor.RazonSocial);


#line default
#line hidden

#line 14 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                                                                                                    __o = Url.Action("AgregarCarrito", "Producto", new { idProveedorProducto = item.IdProveedorProducto });


#line default
#line hidden

#line 15 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                         
                }

#line default
#line hidden

#line 16 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\3\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                           __o = Html.DropDownList("cTipo", (SelectList)ViewBag.listaTipo, "Seleccionar");


#line default
#line hidden
}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ListarProductosDisponibles_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_ListarProductosDisponibles_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                                                         __o = Url.Action("CerrarSesion", "Home");


#line default
#line hidden

#line 3 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                foreach (var item in Model)
                {
                    

#line default
#line hidden

#line 4 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                              __o = Html.DisplayFor(modelItem => item.IdProveedorProducto);


#line default
#line hidden

#line 5 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.IdProducto);


#line default
#line hidden

#line 6 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Nombre);


#line default
#line hidden

#line 7 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Longitud);


#line default
#line hidden

#line 8 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Diametro);


#line default
#line hidden

#line 9 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                           __o = Html.DisplayFor(modelItem => item.PrecioCompra);


#line default
#line hidden

#line 10 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                           __o = Html.DisplayFor(modelItem => item.Producto.PrecioVenta);


#line default
#line hidden

#line 11 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Stock);


#line default
#line hidden

#line 12 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Producto.Tipo.Tipo);


#line default
#line hidden

#line 13 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                       __o = Html.DisplayFor(modelItem => item.Proveedor.RazonSocial);


#line default
#line hidden

#line 14 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                                                                                                    __o = Url.Action("AgregarCarrito", "Producto", new { idProveedorProducto = item.IdProveedorProducto });


#line default
#line hidden

#line 15 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                         
                }

#line default
#line hidden

#line 16 "C:\Users\51966\AppData\Local\Temp\94887996FAD0E52790E26D118B40FCE3D9A3\2\CapaVistaWeb\Views\Producto\ListarProductosDisponibles.cshtml"
                           __o = Html.DropDownList("cTipo", (SelectList)ViewBag.listaTipo, "Seleccionar");


#line default
#line hidden
}
}
}
